apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
spec: 
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-app
        type: frontend-2
    spec:
      containers:
        - name: frontend-container
          image: nginx
  selector:
    matchLabels:
      type: frontend-2
  replicas: 3
 